<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.sonarsource.plugins.secai</groupId>
    <artifactId>secai</artifactId>
    <version>1.1.1</version>

    <modules>
        <module>SonarQubePlugin</module>
    </modules>

    <packaging>pom</packaging>

    <build>
        <plugins>
            <!-- Enforce the usage of '-DskipTests'. To run the tests build the submodules -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>enforce-skip-tests</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <rules>
                                <requireProperty>
                                    <property>skipTests</property>
                                    <message>The whole project can only be build with the '-DskipTests' property</message>
                                </requireProperty>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Assemble zip files for easier installation and docs -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <executions>
                    <execution>
                        <id>existing-sq</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <finalName>secai-for-existing-sq-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>assembly/existing-sq-zip.xml</descriptor>
                            </descriptors>
                            <outputDirectory>release</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>new-sq</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <finalName>secai-for-new-sq-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>assembly/new-sq-zip.xml</descriptor>
                            </descriptors>
                            <outputDirectory>release</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>docs</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <finalName>secai-docs-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>assembly/docs.xml</descriptor>
                            </descriptors>
                            <outputDirectory>release</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>