[supervisord]
nodaemon=true

[program:sonarqube]
command=/opt/sonarqube/bin/linux-x86-64/sonar.sh console
stdout_logfile=/var/log/supervisor/sonarqube.log
stderr_logfile=/var/log/supervisor/sonarqube.err