services:
  flaskapp:
    build: ./Flaskapp
    container_name: flaskapp
    ports:
      - "80:80"
    expose:
      - "80"
    env_file:
      - ./Flaskapp/aifix/.env
    volumes:
      - ./Flaskapp:/app
    restart: unless-stopped