services:
  aifix:
    build: ./AIFix
    container_name: aifix
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./AIFix/.env
    volumes:
      - ./AIFix:/app
    restart: unless-stopped

  confidence:
    build: ./Confidence
    container_name: confidence
    ports:
      - "80:8001"
    expose:
      - "8001"
    volumes:
      - ./Confidence:/app
    restart: unless-stopped