services:
  sonarqube:
    build: .
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - MAVEN_HOME=/opt/maven
      - GRADLE_HOME=/opt/gradle
      - HOST_USER_HOME=/root
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JAVA_PATH=/usr/lib/jvm/java-21-openjdk-amd64/bin/java
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - ./plugins:/opt/sonarqube/extensions/plugins
      - ./projects:/projects
      - /root/secai:/home/sonarqube/secai
    networks:
      -  secai
    restart: always

  aifix:
    build: ./AIFix
    container_name: aifix
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./AIFix/.env
    networks:
      -  secai
    volumes:
      - ./AIFix:/app
    restart: always

  confidence:
    build: ./Confidence
    container_name: confidence
    ports:
      - "80:8001"
    expose:
      - "8001"
    networks:
      - secai
    volumes:
      - ./Confidence:/app
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:

networks:
  secai:
    driver: bridge