name: Documentation Preview

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - reopened
    paths:
      - mkdocs.yml
      - docs/**
      - .github/workflows/documentation-pr-preview.yml

concurrency:
  group: gh-pages

jobs:
  deploy-preview:
    name: Preview documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Documentation Preview
        uses: secure-software-engineering/actions/documentation/pr-preview@develop
        with:
          title: PR ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}